<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../Library.Lending.Contracts/Library.Lending.Contracts.csproj" />
    <ProjectReference Include="../../Library.Lending.Grpc/Library.Lending.Grpc.csproj" />
    <ProjectReference Include="../Library.TestSupport/Library.TestSupport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Reflection" />
  </ItemGroup>
</Project>